name: Atividade GitHub Actions
run-name: ${{ github.actor }} está testando o GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando o código do repositório
        uses: actions/checkout@v4

      - run: echo " O repositório ${{ github.repository }} foi clonado para o runner."

      - name: Setando um ambiente Node
      - uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Listando os arquivos de repositório
        run: |
          ls -la

      - name: Rodando aplicação Node
        run: |
          node App.js

      - run: echo " O status deste trabalho é ${{ job.status }}."